from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from .model import InitializerInfo, ModelInfo
from .naming import macro_name, sanitize_c_identifier


def write_weights_header(model_info: ModelInfo, output_path: Path, *, prefix: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    guard = macro_name(f"{sanitize_c_identifier(prefix, prefix='')}_weights_h")
    exported_initializers = model_info.c_exportable_initializers
    skipped_initializers = [
        item for item in model_info.initializers if not item.is_c_exportable
    ]
    lines: list[str] = [
        "/* Generated by NanoC-NN ONNX Converter. */",
        "/* This file contains float32 ONNX initializers as C99 static constants. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stddef.h>",
        "",
        f"#define {macro_name(prefix)}_WEIGHT_COUNT {len(exported_initializers)}u",
        "",
    ]

    if skipped_initializers:
        lines.append("/* Initializers not exported as C weights: */")
        for initializer in skipped_initializers:
            reason = f"role={initializer.role}, dtype={initializer.elem_type}"
            lines.append(
                f"/* - {initializer.name}: {reason} */"
            )
        lines.append("")

    for initializer in exported_initializers:
        lines.extend(_initializer_to_c(initializer))
        lines.append("")

    lines.extend([f"#endif /* {guard} */", ""])
    output_path.write_text("\n".join(lines), encoding="utf-8")


def _initializer_to_c(initializer: InitializerInfo) -> list[str]:
    symbol = initializer.c_name
    macro = macro_name(symbol)
    lines = [
        f"/* ONNX initializer: {initializer.name} */",
        f"#define {macro}_DIMS {len(initializer.shape)}u",
        f"#define {macro}_SHAPE {{{', '.join(str(item) for item in initializer.shape)}}}",
        f"#define {macro}_SIZE {initializer.element_count}u",
    ]

    if not initializer.is_float32:
        lines.append(f"/* Unsupported data type {initializer.elem_type}; array omitted. */")
        return lines

    values = np.asarray(initializer.array, dtype=np.float32).reshape(-1)
    lines.append(f"static const float {symbol}[{initializer.element_count}] = {{")
    lines.extend(_format_array_values(values))
    lines.append("};")
    return lines


def _format_array_values(values: np.ndarray, line_width: int = 8) -> list[str]:
    lines: list[str] = []
    for start in range(0, len(values), line_width):
        chunk = values[start : start + line_width]
        formatted = ", ".join(_format_float(float(value)) for value in chunk)
        lines.append(f"    {formatted},")
    if not lines:
        lines.append("    0.0f,")
    return lines


def _format_float(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError(f"non-finite weight value cannot be emitted as C literal: {value}")
    text = np.format_float_positional(value, precision=9, unique=False, trim="k")
    if "." not in text and "e" not in text.lower():
        text = f"{text}.0"
    return f"{text}f"
