from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from .model import InitializerInfo, ModelInfo
from .naming import macro_name, sanitize_c_identifier


def write_weights_header(model_info: ModelInfo, output_path: Path, *, prefix: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    guard = macro_name(f"{sanitize_c_identifier(prefix, prefix='')}_weights_h")
    exported_initializers = [
        item for item in model_info.initializers if _is_supported_c_initializer(item)
    ]
    exported_names = {item.name for item in exported_initializers}
    skipped_initializers = [
        item for item in model_info.initializers if item.name not in exported_names
    ]
    lines: list[str] = [
        "/* Generated by NanoC-NN ONNX Converter. */",
        "/* This file contains numeric ONNX initializers as C99 static constants. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define {macro_name(prefix)}_WEIGHT_COUNT {len(model_info.c_exportable_initializers)}u",
        "",
    ]

    if skipped_initializers:
        lines.append("/* Initializers not exported as C weights: */")
        for initializer in skipped_initializers:
            reason = f"role={initializer.role}, dtype={initializer.elem_type}"
            lines.append(
                f"/* - {initializer.name}: {reason} */"
            )
        lines.append("")

    for initializer in exported_initializers:
        lines.extend(_initializer_to_c(initializer))
        lines.append("")

    lines.extend([f"#endif /* {guard} */", ""])
    output_path.write_text("\n".join(lines), encoding="utf-8")


def _initializer_to_c(initializer: InitializerInfo) -> list[str]:
    symbol = initializer.c_name
    macro = macro_name(symbol)
    lines = [
        f"/* ONNX initializer: {initializer.name} */",
        f"#define {macro}_DIMS {len(initializer.shape)}u",
        f"#define {macro}_SHAPE {{{', '.join(str(item) for item in initializer.shape)}}}",
        f"#define {macro}_SIZE {initializer.element_count}u",
    ]

    c_type = _c_type(initializer.elem_type)
    if c_type is None:
        lines.append(f"/* Unsupported data type {initializer.elem_type}; array omitted. */")
        return lines

    values = np.asarray(initializer.array, dtype=_numpy_dtype(initializer.elem_type)).reshape(-1)
    lines.append(f"static const {c_type} {symbol}[{initializer.element_count}] = {{")
    if initializer.elem_type == "FLOAT":
        lines.extend(_format_float_array_values(values.astype(np.float32)))
    else:
        lines.extend(_format_int_array_values(values))
    lines.append("};")
    return lines


def _is_supported_c_initializer(initializer: InitializerInfo) -> bool:
    return _c_type(initializer.elem_type) is not None


def _c_type(elem_type: str) -> str | None:
    return {
        "FLOAT": "float",
        "INT8": "int8_t",
        "UINT8": "uint8_t",
        "INT16": "int16_t",
        "UINT16": "uint16_t",
        "INT32": "int32_t",
        "UINT32": "uint32_t",
        "INT64": "int64_t",
        "UINT64": "uint64_t",
        "BOOL": "uint8_t",
    }.get(elem_type)


def _numpy_dtype(elem_type: str) -> np.dtype:
    return np.dtype(
        {
            "FLOAT": np.float32,
            "INT8": np.int8,
            "UINT8": np.uint8,
            "INT16": np.int16,
            "UINT16": np.uint16,
            "INT32": np.int32,
            "UINT32": np.uint32,
            "INT64": np.int64,
            "UINT64": np.uint64,
            "BOOL": np.uint8,
        }[elem_type]
    )


def _format_float_array_values(values: np.ndarray, line_width: int = 8) -> list[str]:
    lines: list[str] = []
    for start in range(0, len(values), line_width):
        chunk = values[start : start + line_width]
        formatted = ", ".join(_format_float(float(value)) for value in chunk)
        lines.append(f"    {formatted},")
    if not lines:
        lines.append("    0.0f,")
    return lines


def _format_int_array_values(values: np.ndarray, line_width: int = 12) -> list[str]:
    lines: list[str] = []
    flat = values.reshape(-1)
    for start in range(0, len(flat), line_width):
        chunk = flat[start : start + line_width]
        formatted = ", ".join(str(int(value)) for value in chunk)
        lines.append(f"    {formatted},")
    if not lines:
        lines.append("    0,")
    return lines


def _format_float(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError(f"non-finite weight value cannot be emitted as C literal: {value}")
    text = np.format_float_positional(value, precision=9, unique=False, trim="k")
    if "." not in text and "e" not in text.lower():
        text = f"{text}.0"
    return f"{text}f"
