/* Generated by NanoC-NN ONNX Converter. */
/* This file contains numeric ONNX initializers as C99 static constants. */
#ifndef QLINEAR_NUM_003_WEIGHTS_H
#define QLINEAR_NUM_003_WEIGHTS_H

#include <stddef.h>
#include <stdint.h>

#define QLINEAR_NUM_003_WEIGHT_COUNT 0u

/* ONNX initializer: x_scale */
#define QLINEAR_NUM_003_X_SCALE_DIMS 1u
#define QLINEAR_NUM_003_X_SCALE_SHAPE {1}
#define QLINEAR_NUM_003_X_SCALE_SIZE 1u
static const float qlinear_num_003_x_scale[1] = {
    1.000000000f,
};

/* ONNX initializer: x_zp */
#define QLINEAR_NUM_003_X_ZP_DIMS 1u
#define QLINEAR_NUM_003_X_ZP_SHAPE {1}
#define QLINEAR_NUM_003_X_ZP_SIZE 1u
static const uint8_t qlinear_num_003_x_zp[1] = {
    0,
};

/* ONNX initializer: w_scale */
#define QLINEAR_NUM_003_W_SCALE_DIMS 1u
#define QLINEAR_NUM_003_W_SCALE_SHAPE {8}
#define QLINEAR_NUM_003_W_SCALE_SIZE 8u
static const float qlinear_num_003_w_scale[8] = {
    0.008000000f, 0.004500000f, 0.007700000f, 0.003800000f, 0.005400000f, 0.005800000f, 0.004400000f, 0.004500000f,
};

/* ONNX initializer: w_zp */
#define QLINEAR_NUM_003_W_ZP_DIMS 1u
#define QLINEAR_NUM_003_W_ZP_SHAPE {8}
#define QLINEAR_NUM_003_W_ZP_SIZE 8u
static const int8_t qlinear_num_003_w_zp[8] = {
    0, 0, 0, 0, 0, 0, 0, 0,
};

/* ONNX initializer: y_scale */
#define QLINEAR_NUM_003_Y_SCALE_DIMS 1u
#define QLINEAR_NUM_003_Y_SCALE_SHAPE {1}
#define QLINEAR_NUM_003_Y_SCALE_SIZE 1u
static const float qlinear_num_003_y_scale[1] = {
    3.680000067f,
};

/* ONNX initializer: y_zp */
#define QLINEAR_NUM_003_Y_ZP_DIMS 1u
#define QLINEAR_NUM_003_Y_ZP_SHAPE {1}
#define QLINEAR_NUM_003_Y_ZP_SIZE 1u
static const uint8_t qlinear_num_003_y_zp[1] = {
    0,
};

/* ONNX initializer: weight */
#define QLINEAR_NUM_003_WEIGHT_DIMS 4u
#define QLINEAR_NUM_003_WEIGHT_SHAPE {8, 1, 5, 5}
#define QLINEAR_NUM_003_WEIGHT_SIZE 200u
static const int8_t qlinear_num_003_weight[200] = {
    9, -2, 12, 30, -4, -4, 31, 15, -9, 10, -9, -9,
    4, -38, -34, -11, -20, 6, -18, -28, 29, -4, 1, -28,
    -10, 2, -23, 7, -12, -5, -12, 37, 0, -21, 16, -24,
    4, -39, -26, 3, 14, 3, -2, -6, -29, -14, -9, 21,
    6, -35, 6, -7, -13, 12, 20, 18, -16, -6, 6, 19,
    -9, -3, -22, -23, 16, 27, -1, 20, 7, -12, 7, 30,
    0, 31, -52, 16, 1, -5, 1, -39, -4, 7, 29, -10,
    -16, -10, 18, 6, -10, 10, 1, 19, -14, -6, -7, -29,
    5, 5, 0, -4, -28, -8, -6, -16, -3, 8, 37, 3,
    5, -1, -38, 0, 1, 49, -3, 6, 0, -23, 22, 15,
    15, -18, 28, -28, 11, 43, -19, -11, 1, -10, -31, 1,
    -21, 9, -18, 30, -15, -6, 16, -24, 4, 26, -32, 3,
    5, 15, -24, -26, 10, 5, 5, 6, -13, 4, 5, -14,
    37, 9, -23, 13, -19, 15, 23, -16, 19, 8, 16, 37,
    -4, -15, -17, -16, -1, 6, 5, 16, 0, 29, -5, 54,
    12, -17, -21, 9, -4, 14, 9, -1, -16, -30, -8, 17,
    4, -24, 3, 7, -17, 3, 1, -22,
};

/* ONNX initializer: bias */
#define QLINEAR_NUM_003_BIAS_DIMS 1u
#define QLINEAR_NUM_003_BIAS_SHAPE {8}
#define QLINEAR_NUM_003_BIAS_SIZE 8u
static const int32_t qlinear_num_003_bias[8] = {
    17, 28, 54, 52, -68, -46, 25, 25,
};

#endif /* QLINEAR_NUM_003_WEIGHTS_H */
