#ifndef NANOC_TERMINAL_MODEL_CONFIG_H
#define NANOC_TERMINAL_MODEL_CONFIG_H

#define NANOC_TERMINAL_MODEL_INPUT_BYTES 64U
#define NANOC_TERMINAL_MODEL_OUTPUT_BYTES 128U

#endif /* NANOC_TERMINAL_MODEL_CONFIG_H */
