"""
tdd/scripts/cases_registry.py — 测试用例元数据统一注册表

这是用例配置的唯一来源（Single Source of Truth）。
run_tests.py 和 generate_models.py 都从这里读取，不再各自维护分散的字典。

新增用例时只需在 CASE_REGISTRY 里加一条记录；
生成函数在 generate_models.py 的 _GENERATORS 里补充同名条目。
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class NumericCheck:
    dataset_id: str
    input_scale: float = 255.0
    top1_min_match_ratio: float = 1.0
    top1_tie_margin: float = 0.0
    max_abs_error: float | None = None
    max_saturation_ratio: float = 0.5
    float_api: bool = False


@dataclass(frozen=True)
class CaseDef:
    case_id: str
    description: str
    expected: str
    category: str
    required_apis: tuple[str, ...] = field(default_factory=tuple)
    regression: bool = False
    numeric: NumericCheck | None = None
    schema_refs: tuple[str, ...] = field(default_factory=tuple)


CASE_REGISTRY: list[CaseDef] = [
    CaseDef(
        "ABS_001",
        "官方 Abs QDQ/int8 同量化数值精度",
        "ok",
        "core/abs",
        regression=True,
        numeric=NumericCheck(
            dataset_id="abs_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_ABS_QDQ_INT8",),
    ),
    CaseDef(
        "GEMM_001",
        "最小对称 FC 无 bias",
        "ok",
        "core/gemm",
        ("arm_fully_connected_s8",),
        schema_refs=("ONNX_GEMM_QDQ_INT8",),
    ),
    CaseDef(
        "GEMM_002",
        "非对称输入 zp!=0 含 bias",
        "ok",
        "core/gemm",
        ("arm_fully_connected_s8",),
        schema_refs=("ONNX_GEMM_QDQ_INT8",),
    ),
    CaseDef(
        "GEMM_003",
        "非 4 对齐维度 13->7",
        "ok",
        "core/gemm",
        ("arm_fully_connected_s8",),
        schema_refs=("ONNX_GEMM_QDQ_INT8",),
    ),
    CaseDef(
        "GEMM_004",
        "中等规模 64->32",
        "ok",
        "core/gemm",
        ("arm_fully_connected_s8",),
        schema_refs=("ONNX_GEMM_QDQ_INT8",),
    ),
    CaseDef(
        "MATMUL_001",
        "官方 MatMul QDQ/int8 FC-compatible 形态",
        "ok",
        "core/matmul",
        ("arm_fully_connected_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="matmul_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.08,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_MATMUL_QDQ_INT8",),
    ),
    CaseDef(
        "FLATTEN_001",
        "官方 Flatten QDQ/int8 axis=1 数值顺序",
        "ok",
        "core/flatten",
        regression=True,
        numeric=NumericCheck(
            dataset_id="flatten_axis1_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_FLATTEN_QDQ_INT8",),
    ),
    CaseDef(
        "RESHAPE_001",
        "官方 Reshape QDQ/int8 静态形状数值顺序",
        "ok",
        "core/reshape",
        regression=True,
        numeric=NumericCheck(
            dataset_id="reshape_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_RESHAPE_QDQ_INT8",),
    ),
    CaseDef(
        "SQUEEZE_001",
        "官方 Squeeze QDQ/int8 静态去 1 维数值顺序",
        "ok",
        "core/squeeze",
        regression=True,
        numeric=NumericCheck(
            dataset_id="squeeze_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_SQUEEZE_QDQ_INT8",),
    ),
    CaseDef(
        "CONV_001",
        "1x1 pointwise 单通道",
        "ok",
        "core/conv",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_CONV_RANK4_QDQ_INT8",),
    ),
    CaseDef(
        "CONV_002",
        "3x3 标准 SAME padding",
        "ok",
        "core/conv",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_CONV_RANK4_QDQ_INT8",),
    ),
    CaseDef(
        "CONV_003",
        "stride=2 下采样",
        "ok",
        "core/conv",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_CONV_RANK4_QDQ_INT8",),
    ),
    CaseDef(
        "CONV_004",
        "非对称输入 zp!=0",
        "ok",
        "core/conv",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_CONV_RANK4_QDQ_INT8",),
    ),
    CaseDef(
        "MAXPOOL_001",
        "标准 2x2 stride=2 MaxPool int8 代码生成",
        "ok",
        "core/maxpool",
        ("arm_max_pool_s8",),
        regression=True,
        schema_refs=("ONNX_MAXPOOL_QDQ_INT8",),
    ),
    CaseDef(
        "MAXPOOL_002",
        "SqueezeNet 风格 DQ/MaxPool/Q int8 边界代码生成",
        "ok",
        "core/maxpool",
        ("arm_max_pool_s8",),
        regression=True,
        schema_refs=("ONNX_MAXPOOL_QDQ_INT8",),
    ),
    CaseDef(
        "AVGPOOL_001",
        "QLinearGlobalAveragePool int8 全局池化代码生成",
        "ok",
        "core/avgpool",
        ("arm_avgpool_s8",),
        regression=True,
        schema_refs=("ONNX_QGLOBALAVGPOOL_INT8",),
    ),
    CaseDef(
        "AVGPOOL_002",
        "官方 GlobalAveragePool QDQ/int8 全局池化数值精度",
        "ok",
        "core/avgpool",
        ("arm_avgpool_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="avgpool_global_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.06,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_GLOBALAVGPOOL_QDQ_INT8",),
    ),
    CaseDef(
        "AVGPOOL_003",
        "官方 AveragePool QDQ/int8 2x2 stride=2 数值精度",
        "ok",
        "core/avgpool",
        ("arm_avgpool_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="avgpool_window_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.06,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_AVERAGEPOOL_QDQ_INT8",),
    ),
    CaseDef(
        "SOFTMAX_001",
        "10 分类 Softmax int8 代码生成",
        "ok",
        "core/softmax",
        ("arm_softmax_s8",),
        regression=True,
        schema_refs=("ONNX_SOFTMAX_QDQ_INT8",),
    ),
    CaseDef(
        "SOFTMAX_002",
        "SqueezeNet 末端 float output Softmax int8 C 输出",
        "ok",
        "core/softmax",
        ("arm_softmax_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="softmax_float_output_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.02,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_SOFTMAX_QDQ_INT8",),
    ),
    CaseDef(
        "CONCAT_001",
        "rank=4 channel 维 int8 Concat 数值精度",
        "ok",
        "core/concat",
        ("arm_concatenation_s8_z",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="concat_channel_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.11,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_CONCAT_QDQ_INT8",),
    ),
    CaseDef(
        "CONCAT_002",
        "SqueezeNet 风格不同量化分支 Concat 数值精度",
        "ok",
        "core/concat",
        ("arm_concatenation_s8_z",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="concat_requant_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.21,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_CONCAT_QDQ_INT8",),
    ),
    CaseDef(
        "ADD_001",
        "官方 Add QDQ/int8 同形状常量分支数值精度",
        "ok",
        "core/add",
        ("arm_elementwise_add_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="add_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.08,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_ADD_QDQ_INT8",),
    ),
    CaseDef(
        "MUL_001",
        "官方 Mul QDQ/int8 同形状常量分支数值精度",
        "ok",
        "core/mul",
        ("arm_elementwise_mul_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="mul_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.08,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_MUL_QDQ_INT8",),
    ),
    CaseDef(
        "SUB_001",
        "官方 Sub QDQ/int8 同形状常量分支数值精度",
        "ok",
        "core/sub",
        regression=True,
        numeric=NumericCheck(
            dataset_id="sub_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.08,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_SUB_QDQ_INT8",),
    ),
    CaseDef(
        "DIV_001",
        "官方 Div QDQ/int8 同形状非零常量分支数值精度",
        "ok",
        "core/div",
        regression=True,
        numeric=NumericCheck(
            dataset_id="div_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.08,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_DIV_QDQ_INT8",),
    ),
    CaseDef(
        "SIGMOID_001",
        "官方 Sigmoid QDQ/int8 静态张量数值精度",
        "ok",
        "core/sigmoid",
        regression=True,
        numeric=NumericCheck(
            dataset_id="sigmoid_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.01,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_SIGMOID_QDQ_INT8",),
    ),
    CaseDef(
        "PAD_001",
        "官方 Pad QDQ/int8 rank4 constant mode 数值顺序",
        "ok",
        "core/pad",
        regression=True,
        numeric=NumericCheck(
            dataset_id="pad_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_PAD_QDQ_INT8",),
    ),
    CaseDef(
        "SLICE_001",
        "官方 Slice QDQ/int8 静态区间数值顺序",
        "ok",
        "core/slice",
        regression=True,
        numeric=NumericCheck(
            dataset_id="slice_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_SLICE_QDQ_INT8",),
    ),
    CaseDef(
        "GATHER_001",
        "官方 Gather QDQ/int8 静态 indices 数值顺序",
        "ok",
        "core/gather",
        regression=True,
        numeric=NumericCheck(
            dataset_id="gather_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_GATHER_QDQ_INT8",),
    ),
    CaseDef(
        "TRANSPOSE_001",
        "官方 Transpose QDQ/int8 rank4 显式 perm 数值顺序",
        "ok",
        "core/transpose",
        ("arm_transpose_s8",),
        regression=True,
        numeric=NumericCheck(
            dataset_id="transpose_qdq_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.0,
            max_saturation_ratio=0.25,
        ),
        schema_refs=("ONNX_TRANSPOSE_QDQ_INT8",),
    ),
    CaseDef(
        "TOPO_001",
        "Conv->Relu->Pool->Flatten->FC 组合链路",
        "ok",
        "topology",
        ("arm_convolve_wrapper_s8", "arm_max_pool_s8", "arm_fully_connected_s8"),
        schema_refs=(
            "ONNX_CONV_RANK4_QDQ_INT8",
            "ONNX_MAXPOOL_QDQ_INT8",
            "ONNX_GEMM_QDQ_INT8",
        ),
    ),
    CaseDef(
        "TOPO_002",
        "Conv1d->Relu->Conv1d->Relu->Flatten->FC 时序分类链路",
        "ok",
        "topology",
        ("arm_convolve_wrapper_s8", "arm_fully_connected_s8"),
        schema_refs=("ONNX_CONV_RANK3_QDQ_INT8", "ONNX_GEMM_QDQ_INT8"),
    ),
    CaseDef(
        "TOPO_003",
        "真实 MNIST QLinear int8 分类链路",
        "ok",
        "topology",
        (
            "arm_convolve_wrapper_s8",
            "arm_max_pool_s8",
            "arm_fully_connected_per_channel_s8",
            "arm_elementwise_add_s8",
        ),
        regression=True,
        numeric=NumericCheck(
            dataset_id="mnist_synthetic_smoke",
            input_scale=255.0,
            top1_min_match_ratio=1.0,
            max_saturation_ratio=0.5,
        ),
        schema_refs=(
            "ONNX_QLINEARCONV_PER_CHANNEL",
            "ONNX_MAXPOOL_QDQ_INT8",
            "ONNX_QLINEARADD_INT8",
            "ONNX_QLINEARMATMUL_INT8",
        ),
    ),
    CaseDef(
        "NET_001",
        "真实 SqueezeNet 1.0 int8 图像分类网络导入评估",
        "ok",
        "networks",
        (
            "arm_convolve_wrapper_s8",
            "arm_max_pool_s8",
            "arm_concatenation_s8_z",
            "arm_avgpool_s8",
            "arm_softmax_s8",
        ),
        regression=True,
        numeric=NumericCheck(
            dataset_id="net_001_squeezenet_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            top1_tie_margin=0.02,
            max_abs_error=0.21,
            max_saturation_ratio=0.75,
        ),
        schema_refs=("ONNX_SQUEEZENET_QDQ_INT8",),
    ),
    CaseDef(
        "NET_002",
        "真实 MobileNetV2 int8/QLinear 图像分类网络导入评估",
        "ok",
        "networks",
        (
            "arm_convolve_wrapper_s8",
            "arm_depthwise_conv_wrapper_s8",
            "arm_elementwise_add_s8",
            "arm_avgpool_s8",
            "arm_fully_connected_per_channel_s8",
        ),
        regression=False,
        schema_refs=(
            "ONNX_CONV_RANK4_QDQ_INT8",
            "ONNX_CONV_DEPTHWISE_QDQ_INT8",
            "ONNX_QLINEARADD_INT8",
            "ONNX_QGLOBALAVGPOOL_INT8",
            "ONNX_QLINEARMATMUL_INT8",
        ),
    ),
    CaseDef(
        "NET_003",
        "真实 SSD-MobileNet int8 目标检测网络导入评估",
        "unsupported",
        "networks",
        regression=False,
        schema_refs=("ONNX_SSD_MOBILENET_UNSUPPORTED",),
    ),
    CaseDef(
        "NET_004",
        "KWS DS-CNN-style int8 网络导入评估",
        "ok",
        "networks",
        (
            "arm_convolve_wrapper_s8",
            "arm_depthwise_conv_wrapper_s8",
            "arm_max_pool_s8",
            "arm_fully_connected_s8",
        ),
        regression=False,
        schema_refs=(
            "ONNX_CONV_RANK4_QDQ_INT8",
            "ONNX_CONV_DEPTHWISE_QDQ_INT8",
            "ONNX_MAXPOOL_QDQ_INT8",
            "ONNX_GEMM_QDQ_INT8",
        ),
    ),
    CaseDef(
        "NET_005",
        "Tiny signal jump int8 时序分类网络导入评估",
        "ok",
        "networks",
        (
            "arm_convolve_wrapper_s8",
            "arm_fully_connected_s8",
        ),
        regression=True,
        numeric=NumericCheck(
            dataset_id="net_005_signal_jump_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_saturation_ratio=0.5,
        ),
        schema_refs=("ONNX_CONV_RANK3_QDQ_INT8", "ONNX_GEMM_QDQ_INT8"),
    ),
    CaseDef(
        "NET_006",
        "EfficientNet-Lite4 int8 小型图像分类网络导入评估",
        "unsupported",
        "networks",
        regression=False,
        schema_refs=("ONNX_EFFICIENTNET_LITE_UNSUPPORTED",),
    ),
    CaseDef(
        "TS_001",
        "CWRU bearing vibration MLP float C reference 数值回归",
        "ok",
        "networks",
        regression=True,
        numeric=NumericCheck(
            dataset_id="timeseries_cwru_bearing_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=1e-4,
            max_saturation_ratio=1.0,
            float_api=True,
        ),
        schema_refs=("ONNX_FLOAT_REFERENCE_STATIC",),
    ),
    CaseDef(
        "TS_002",
        "KWS DS-CNN PTQ INT8 Q/DQ float C reference 数值回归",
        "ok",
        "networks",
        regression=True,
        numeric=NumericCheck(
            dataset_id="timeseries_kws_dscnn_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=1e-4,
            max_saturation_ratio=1.0,
            float_api=True,
        ),
        schema_refs=("ONNX_FLOAT_REFERENCE_STATIC",),
    ),
    CaseDef(
        "TS_003",
        "KWS DS-CNN QAT INT8 Q/DQ float C reference 数值回归",
        "ok",
        "networks",
        regression=True,
        numeric=NumericCheck(
            dataset_id="timeseries_kws_dscnn_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=0.2,
            max_saturation_ratio=1.0,
            float_api=True,
        ),
        schema_refs=("ONNX_FLOAT_REFERENCE_STATIC",),
    ),
    CaseDef(
        "TS_004",
        "MET hybrid 双输入 float C reference 数值回归",
        "ok",
        "networks",
        regression=True,
        numeric=NumericCheck(
            dataset_id="timeseries_met_hybrid_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=1e-4,
            max_saturation_ratio=1.0,
            float_api=True,
        ),
        schema_refs=("ONNX_FLOAT_REFERENCE_STATIC",),
    ),
    CaseDef(
        "TS_005",
        "STWIN vowel IMU CNN float C reference 数值回归",
        "ok",
        "networks",
        regression=True,
        numeric=NumericCheck(
            dataset_id="timeseries_stwin_vowel_smoke",
            input_scale=1.0,
            top1_min_match_ratio=1.0,
            max_abs_error=1e-4,
            max_saturation_ratio=1.0,
            float_api=True,
        ),
        schema_refs=("ONNX_FLOAT_REFERENCE_STATIC",),
    ),
    CaseDef(
        "QLINEAR_NUM_001",
        "QLinearConv uint8 输入数值精度 (CMSIS-NN vs ONNX)",
        "ok",
        "core/qlinear",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_QLINEARCONV_UINT8",),
    ),
    CaseDef(
        "QLINEAR_NUM_002",
        "多通道 QLinearConv + bias + per-channel scale",
        "ok",
        "core/qlinear",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_QLINEARCONV_PER_CHANNEL",),
    ),
    CaseDef(
        "QLINEAR_NUM_003",
        "高通道 QLinearConv 5×5 per-channel (仿 MNIST Conv1)",
        "ok",
        "core/qlinear",
        ("arm_convolve_wrapper_s8",),
        schema_refs=("ONNX_QLINEARCONV_PER_CHANNEL",),
    ),
    CaseDef(
        "NEG_001",
        "float32 无 Q/DQ 模型正确拒绝",
        "blocked",
        "negative",
        schema_refs=("ONNX_FLOAT_NO_QDQ_BLOCKED",),
    ),
]

CASE_MAP: dict[str, CaseDef] = {c.case_id: c for c in CASE_REGISTRY}
