"""
tdd/scripts/support_matrix.py — ONNX schema driven support matrix.

This module is the machine-readable bridge between ONNX operator schema forms
and NanoC-NN TDD cases.  Cases must reference one or more support IDs from this
file; no case should stand outside the ONNX-schema-driven tree.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SupportEntry:
    support_id: str
    schema_source: str
    domain: str
    op_type: str
    opset_range: str
    schema_form: str
    lowering: str
    backend: str
    capability_type: str
    status: str
    cmsis_apis: tuple[str, ...] = field(default_factory=tuple)
    planned: bool = False
    notes: str = ""


SUPPORT_MATRIX: tuple[SupportEntry, ...] = (
    SupportEntry(
        support_id="ONNX_ABS_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Abs",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, same input/output quantization",
        lowering="generated_c_abs_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="CMSIS-NN has no dedicated s8 Abs kernel; generated C clamps -128 to 127.",
    ),
    SupportEntry(
        support_id="ONNX_CONV_RANK4_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Conv",
        opset_range="11+",
        schema_form="rank=4 NCHW, group=1, static shape, QDQ/int8 parameters",
        lowering="cmsis_conv2d_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_convolve_wrapper_s8",),
    ),
    SupportEntry(
        support_id="ONNX_AVERAGEPOOL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="AveragePool",
        opset_range="11+",
        schema_form="rank=4 static NCHW, QDQ/int8 tensor, CMSIS-compatible average pool window",
        lowering="cmsis_avgpool_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_avgpool_s8",),
    ),
    SupportEntry(
        support_id="ONNX_CONV_RANK3_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Conv",
        opset_range="11+",
        schema_form="rank=3 NCW, group=1, static shape, QDQ/int8 parameters",
        lowering="cmsis_conv1d_as_2d_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_convolve_wrapper_s8",),
        notes="Business-facing Conv1d cases are ONNX Conv rank=3 forms.",
    ),
    SupportEntry(
        support_id="ONNX_CONV_DEPTHWISE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Conv",
        opset_range="11+",
        schema_form="rank=4, group=input_channels, depthwise multiplier, QDQ/int8 parameters",
        lowering="cmsis_depthwise_conv2d_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_depthwise_conv_wrapper_s8",),
    ),
    SupportEntry(
        support_id="ONNX_GEMM_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Gemm",
        opset_range="11+",
        schema_form="static 2-D fully connected form, optional bias, QDQ/int8 parameters",
        lowering="cmsis_fully_connected_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_fully_connected_s8",),
    ),
    SupportEntry(
        support_id="ONNX_FLATTEN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Flatten",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, axis=1, preserves ONNX row-major flatten order",
        lowering="generation_time_shape_alias_or_layout_copy",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Layout operator with no CMSIS kernel; protects NCHW/NHWC flatten order before FC.",
    ),
    SupportEntry(
        support_id="ONNX_RESHAPE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Reshape",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, constant shape, same element count",
        lowering="generation_time_shape_alias_or_layout_copy",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Shape-only operator with no CMSIS kernel; first form preserves linear storage order.",
    ),
    SupportEntry(
        support_id="ONNX_SQUEEZE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Squeeze",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, explicit axes removing dimensions of size 1",
        lowering="generation_time_shape_alias_or_layout_copy",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Shape-only operator with no CMSIS kernel; first form preserves linear storage order.",
    ),
    SupportEntry(
        support_id="ONNX_MATMUL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="MatMul",
        opset_range="11+",
        schema_form="static fully connected compatible form, QDQ/int8 parameters",
        lowering="cmsis_fully_connected_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_fully_connected_s8",),
        notes="Supports A[1,I] x B[I,O] classifier-head form by transposing constant weights for CMSIS-NN FC.",
    ),
    SupportEntry(
        support_id="ONNX_MAXPOOL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="MaxPool",
        opset_range="11+",
        schema_form="rank=4 static NCHW, QDQ/int8 tensor, CMSIS-compatible pool window",
        lowering="cmsis_maxpool_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_max_pool_s8",),
    ),
    SupportEntry(
        support_id="ONNX_ADD_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Add",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, second input may be constant",
        lowering="cmsis_elementwise_add_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_elementwise_add_s8",),
    ),
    SupportEntry(
        support_id="ONNX_MUL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Mul",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, second input may be constant",
        lowering="cmsis_elementwise_mul_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_elementwise_mul_s8",),
    ),
    SupportEntry(
        support_id="ONNX_SUB_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Sub",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, second input may be constant",
        lowering="generated_c_sub_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="CMSIS-NN has no dedicated s8 Sub kernel; generated C dequantizes, subtracts and requantizes.",
    ),
    SupportEntry(
        support_id="ONNX_DIV_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Div",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, non-zero second input may be constant",
        lowering="generated_c_div_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form protects finite denominators; generated C clamps division-by-near-zero defensively.",
    ),
    SupportEntry(
        support_id="ONNX_SIGMOID_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Sigmoid",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_sigmoid_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Generated C uses expf for the first correctness baseline; future work may replace it with a LUT.",
    ),
    SupportEntry(
        support_id="ONNX_TANH_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Tanh",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_tanh_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Generated C uses tanhf as the correctness baseline before fixed-point/LUT optimization.",
    ),
    SupportEntry(
        support_id="ONNX_LEAKYRELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="LeakyRelu",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, scalar alpha attribute",
        lowering="generated_c_leakyrelu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form supports alpha=0.1 in TDD; generated C dequantizes, applies branch, and requantizes.",
    ),
    SupportEntry(
        support_id="ONNX_CLIP_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Clip",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor with constant min/max inputs or legacy attributes",
        lowering="generated_c_clip_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Standalone data-path Clip lowers to generated C; activation fusion remains a separate optimization.",
    ),
    SupportEntry(
        support_id="ONNX_NEG_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Neg",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_neg_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_SQRT_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Sqrt",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, non-negative value domain",
        lowering="generated_c_sqrt_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Generated C clamps negative roundoff/domain values to zero for the first MCU-safe baseline.",
    ),
    SupportEntry(
        support_id="ONNX_RECIPROCAL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Reciprocal",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, non-zero finite value domain",
        lowering="generated_c_reciprocal_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Generated C guards near-zero denominators to avoid undefined MCU behavior.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCEMEAN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceMean",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducemean_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form protects row-wise temporal/channel feature averaging for small embedded models.",
    ),
    SupportEntry(
        support_id="ONNX_UNSQUEEZE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Unsqueeze",
        opset_range="11+",
        schema_form="static data-path QDQ/int8 tensor, constant axes, element count unchanged",
        lowering="generated_c_unsqueeze_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Shape-helper Unsqueeze remains folded; quantized data-path Unsqueeze is an explicit copy.",
    ),
    SupportEntry(
        support_id="ONNX_EXP_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Exp",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, bounded input domain",
        lowering="generated_c_exp_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Generated C uses expf as correctness baseline and relies on TDD input range to avoid saturation.",
    ),
    SupportEntry(
        support_id="ONNX_LOG_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Log",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, positive input domain",
        lowering="generated_c_log_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form requires strictly positive inputs; generated C guards non-positive values.",
    ),
    SupportEntry(
        support_id="ONNX_FLOOR_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Floor",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_floor_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_CEIL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Ceil",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_ceil_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_ROUND_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Round",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_round_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="ONNX Round uses round-to-nearest-even; generated C mirrors that with nearbyintf.",
    ),
    SupportEntry(
        support_id="ONNX_SIGN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Sign",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_sign_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_MIN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Min",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, second input may be constant",
        lowering="generated_c_min_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_MAX_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Max",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, second input may be constant",
        lowering="generated_c_max_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_POW_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Pow",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, finite value domain",
        lowering="generated_c_pow_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form uses non-negative bases and small positive exponents to avoid NaN/Inf.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCESUM_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceSum",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducesum_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_REDUCEMAX_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceMax",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducemax_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_REDUCEMIN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceMin",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducemin_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_WHERE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Where",
        opset_range="11+",
        schema_form="static bool condition, same-shape QDQ/int8 then/else tensors",
        lowering="generated_c_where_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="First form keeps bool as an internal condition tensor and returns QDQ/int8 data.",
    ),
    SupportEntry(
        support_id="ONNX_EQUAL_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Equal",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, bool output consumed by Where",
        lowering="generated_c_equal_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Protected through Equal->Where because current numeric runner validates int8 model outputs.",
    ),
    SupportEntry(
        support_id="ONNX_GREATER_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Greater",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, bool output consumed by Where",
        lowering="generated_c_greater_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Protected through Greater->Where because current numeric runner validates int8 model outputs.",
    ),
    SupportEntry(
        support_id="ONNX_LESS_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Less",
        opset_range="11+",
        schema_form="same-shape QDQ/int8 tensors, bool output consumed by Where",
        lowering="generated_c_less_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Protected through Less->Where because current numeric runner validates int8 model outputs.",
    ),
    SupportEntry(
        support_id="ONNX_GREATEROREQUAL_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="GreaterOrEqual",
        opset_range="12+",
        schema_form="same-shape QDQ/int8 tensors, bool output consumed by Where",
        lowering="generated_c_greaterorequal_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Protected through GreaterOrEqual->Where because current numeric runner validates int8 model outputs.",
    ),
    SupportEntry(
        support_id="ONNX_LESSOREQUAL_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="LessOrEqual",
        opset_range="12+",
        schema_form="same-shape QDQ/int8 tensors, bool output consumed by Where",
        lowering="generated_c_lessorequal_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Protected through LessOrEqual->Where because current numeric runner validates int8 model outputs.",
    ),
    SupportEntry(
        support_id="ONNX_AND_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="And",
        opset_range="7+",
        schema_form="two bool intermediate tensors (compare outputs), bool output consumed by Where",
        lowering="generated_c_and_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Bool tensors are internal 0/1 int8 buffers produced by compare ops and consumed by Where.",
    ),
    SupportEntry(
        support_id="ONNX_OR_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Or",
        opset_range="7+",
        schema_form="two bool intermediate tensors (compare outputs), bool output consumed by Where",
        lowering="generated_c_or_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Bool tensors are internal 0/1 int8 buffers produced by compare ops and consumed by Where.",
    ),
    SupportEntry(
        support_id="ONNX_NOT_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Not",
        opset_range="7+",
        schema_form="single bool intermediate tensor (compare output), bool output consumed by Where",
        lowering="generated_c_not_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Bool tensors are internal 0/1 int8 buffers produced by compare ops and consumed by Where.",
    ),
    SupportEntry(
        support_id="ONNX_XOR_QDQ_BOOL",
        schema_source="official",
        domain="ai.onnx",
        op_type="Xor",
        opset_range="7+",
        schema_form="two bool intermediate tensors (compare outputs), bool output consumed by Where",
        lowering="generated_c_xor_bool",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Bool tensors are internal 0/1 int8 buffers produced by compare ops and consumed by Where.",
    ),
    SupportEntry(
        support_id="ONNX_ERF_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Erf",
        opset_range="9+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_erf_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline via erff; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_SOFTPLUS_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Softplus",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_softplus_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline via log1pf(expf); tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_SOFTSIGN_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Softsign",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_softsign_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline via fabsf division; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_HARDSWISH_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="HardSwish",
        opset_range="14+",
        schema_form="static QDQ/int8 tensor",
        lowering="generated_c_hardswish_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline via fminf/fmaxf relu6; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_ELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Elu",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor, alpha attribute",
        lowering="generated_c_elu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline with alpha attribute; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_SELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Selu",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor, alpha/gamma attributes",
        lowering="generated_c_selu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline with alpha/gamma attributes; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_HARDSIGMOID_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="HardSigmoid",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor, alpha/beta attributes",
        lowering="generated_c_hardsigmoid_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline with alpha/beta attributes; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_THRESHOLDEDRELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ThresholdedRelu",
        opset_range="1+",
        schema_form="static QDQ/int8 tensor, alpha attribute",
        lowering="generated_c_thresholdedrelu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline via exact threshold comparison; exact match expected.",
    ),
    SupportEntry(
        support_id="ONNX_CELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Celu",
        opset_range="12+",
        schema_form="static QDQ/int8 tensor, alpha attribute",
        lowering="generated_c_celu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline with alpha attribute; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_PRELU_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="PRelu",
        opset_range="1+",
        schema_form="same-shape QDQ/int8 tensor, constant quantized slope input",
        lowering="generated_c_prelu_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 correctness baseline with constant quantized slope; tolerance 1 int8 unit for ULP boundary.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCELOGSUM_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceLogSum",
        opset_range="13+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducelogsum_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 row reduce via sum + logf; tolerance 1 int8 unit for quantization boundary.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCELOGSUMEXP_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceLogSumExp",
        opset_range="13+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducelogsumexp_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 row reduce via sum(expf) + logf; tolerance 1 int8 unit for quantization boundary.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCESUMSQUARE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceSumSquare",
        opset_range="13+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducesumsquare_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="C99 row reduce via sum of squares; tolerance 1 int8 unit for quantization boundary.",
    ),
    SupportEntry(
        support_id="ONNX_REDUCEPROD_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceProd",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reduceprod_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_REDUCEL1_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceL1",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducel1_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_REDUCEL2_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="ReduceL2",
        opset_range="11+",
        schema_form="rank=2 static QDQ/int8 tensor, axes=1, keepdims=1",
        lowering="generated_c_reducel2_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_PAD_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Pad",
        opset_range="11+",
        schema_form="static rank=4 QDQ/int8 tensor, constant mode, constant pads initializer",
        lowering="generated_c_pad_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
    ),
    SupportEntry(
        support_id="ONNX_SLICE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Slice",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, constant starts/ends/axes/steps",
        lowering="generated_c_slice_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Shape-helper Slice remains folded; data Slice lowers to generated C.",
    ),
    SupportEntry(
        support_id="ONNX_GATHER_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Gather",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, constant indices, one axis",
        lowering="generated_c_gather_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(),
        notes="Shape-helper Gather remains folded; data Gather lowers to generated C.",
    ),
    SupportEntry(
        support_id="ONNX_GLOBALAVGPOOL_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="GlobalAveragePool",
        opset_range="11+",
        schema_form="rank=4 static NCHW, QDQ/int8 tensor, full spatial H/W average",
        lowering="cmsis_global_avgpool_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_avgpool_s8",),
        notes="Official ONNX GlobalAveragePool form observed in KWS and time-series fixtures.",
    ),
    SupportEntry(
        support_id="ONNX_SOFTMAX_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Softmax",
        opset_range="11+",
        schema_form="static classification vector, int8 output path",
        lowering="cmsis_softmax_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_softmax_s8",),
    ),
    SupportEntry(
        support_id="ONNX_QLINEARCONV_UINT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="QLinearConv",
        opset_range="10+",
        schema_form="uint8 activation, static rank=4, CMSIS-compatible convolution",
        lowering="cmsis_qlinearconv_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_convolve_wrapper_s8",),
    ),
    SupportEntry(
        support_id="ONNX_QLINEARCONV_PER_CHANNEL",
        schema_source="official",
        domain="ai.onnx",
        op_type="QLinearConv",
        opset_range="10+",
        schema_form="static rank=4 convolution with per-channel weight scale",
        lowering="cmsis_qlinearconv_per_channel_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_convolve_wrapper_s8",),
    ),
    SupportEntry(
        support_id="ONNX_QLINEARADD_INT8",
        schema_source="extension",
        domain="nanoc.observed",
        op_type="QLinearAdd",
        opset_range="10+",
        schema_form="two static int8 tensors or activation plus bias-like tensor",
        lowering="cmsis_elementwise_add_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_elementwise_add_s8",),
        notes="Observed in quantized fixtures, but not present in official ONNX 1.22.0 schema catalog.",
    ),
    SupportEntry(
        support_id="ONNX_QGLOBALAVGPOOL_INT8",
        schema_source="extension",
        domain="nanoc.observed",
        op_type="QLinearGlobalAveragePool",
        opset_range="10+",
        schema_form="static rank=4 quantized global average pool",
        lowering="cmsis_avgpool_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_avgpool_s8",),
        notes="Observed in quantized fixtures, but not present in official ONNX 1.22.0 schema catalog.",
    ),
    SupportEntry(
        support_id="ONNX_QLINEARMATMUL_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="QLinearMatMul",
        opset_range="21+",
        schema_form="static fully connected compatible quantized matmul",
        lowering="cmsis_fully_connected_per_channel_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_fully_connected_per_channel_s8",),
    ),
    SupportEntry(
        support_id="ONNX_CONCAT_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Concat",
        opset_range="11+",
        schema_form="rank=4 NCHW, axis=1 channel concat, same-quantization QDQ/int8 tensors",
        lowering="cmsis_concatenation_s8_z",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_concatenation_s8_z",),
        notes="First protected form is the SqueezeNet-style channel concatenation branch.",
    ),
    SupportEntry(
        support_id="ONNX_TRANSPOSE_QDQ_INT8",
        schema_source="official",
        domain="ai.onnx",
        op_type="Transpose",
        opset_range="11+",
        schema_form="static QDQ/int8 tensor, rank=4 explicit perm",
        lowering="cmsis_transpose_s8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=("arm_transpose_s8",),
    ),
    SupportEntry(
        support_id="ONNX_FLOAT_REFERENCE_STATIC",
        schema_source="mixed",
        domain="ai.onnx",
        op_type="multiple",
        opset_range="11+",
        schema_form="static-shape float or QDQ graph executed by generated C reference backend",
        lowering="c99_reference_runtime",
        backend="c-reference",
        capability_type="reference_float",
        status="ok",
        notes="Verification backend only; not a CMSIS-NN int8 delivery claim.",
    ),
    SupportEntry(
        support_id="ONNX_FLOAT_NO_QDQ_BLOCKED",
        schema_source="mixed",
        domain="ai.onnx",
        op_type="multiple",
        opset_range="11+",
        schema_form="internal float32 graph without QDQ quantization section",
        lowering="reject_without_quantization",
        backend="reject",
        capability_type="negative",
        status="blocked",
        notes="Protects the CMSIS-NN int8 product boundary.",
    ),
    SupportEntry(
        support_id="ONNX_SQUEEZENET_QDQ_INT8",
        schema_source="mixed",
        domain="ai.onnx",
        op_type="multiple",
        opset_range="10+",
        schema_form="SqueezeNet int8 with QLinearConv, MaxPool, DQ/Concat/Q, QLinearGlobalAveragePool and terminal Softmax",
        lowering="cmsis_nn_squeezenet_int8",
        backend="cmsis-nn",
        capability_type="cmsis_int8",
        status="ok",
        cmsis_apis=(
            "arm_convolve_wrapper_s8",
            "arm_max_pool_s8",
            "arm_concatenation_s8_z",
            "arm_avgpool_s8",
            "arm_softmax_s8",
        ),
        notes="Full structure generation and C99 smoke run are supported; numeric ImageNet smoke remains a follow-up.",
    ),
    SupportEntry(
        support_id="ONNX_SSD_MOBILENET_UNSUPPORTED",
        schema_source="mixed",
        domain="ai.onnx",
        op_type="multiple",
        opset_range="10+",
        schema_form="SSD-MobileNet detection graph with multi-output heads/dynamic or postprocess ops",
        lowering="unsupported_detection_boundary",
        backend="reject",
        capability_type="import_boundary",
        status="unsupported",
    ),
    SupportEntry(
        support_id="ONNX_EFFICIENTNET_LITE_UNSUPPORTED",
        schema_source="mixed",
        domain="ai.onnx",
        op_type="multiple",
        opset_range="10+",
        schema_form="EfficientNet-Lite quantized graph forms outside current layout/op whitelist",
        lowering="unsupported_import_boundary",
        backend="reject",
        capability_type="import_boundary",
        status="unsupported",
    ),
)

SUPPORT_MAP: dict[str, SupportEntry] = {
    entry.support_id: entry for entry in SUPPORT_MATRIX
}

VALID_SUPPORT_STATUSES = {"ok", "blocked", "unsupported", "oversize"}
VALID_BACKENDS = {"cmsis-nn", "c-reference", "reject"}
VALID_CAPABILITY_TYPES = {
    "cmsis_int8",
    "reference_float",
    "negative",
    "import_boundary",
}
VALID_SCHEMA_SOURCES = {"official", "extension", "mixed"}
