#ifndef NANOC_STATUS_H
#define NANOC_STATUS_H

typedef enum {
    NANOC_STATUS_OK = 0,
    NANOC_STATUS_ERR_PROTOCOL = 1,
    NANOC_STATUS_ERR_UNKNOWN_CMD = 2,
    NANOC_STATUS_ERR_UNKNOWN_CASE = 3,
    NANOC_STATUS_ERR_INPUT_SIZE = 4,
    NANOC_STATUS_ERR_OUTPUT_SIZE = 5,
    NANOC_STATUS_ERR_MODEL_RUN = 6,
    NANOC_STATUS_ERR_UART = 7,
} nanoc_status_t;

#endif /* NANOC_STATUS_H */
